In [15]:
#linear systems 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Problem 1

In [38]:
#12x + 3y = 162 and 8x + 3y = 122

A = np.array([[12,3],[8,3]])
b = np.array([[162],[122]])

#verfiy the size
print("dim. of matrix A=", A.shape)

#find the det(A)  
det= np.linalg.det(A)
print("\n", det)

#defining the inverse 
inv_A = np.linalg.inv(A) 
print("\n", inv_A)

#find the solution
sol = inv_A.dot(b)
print("\n",sol)

dim. of matrix A= (2, 2)

 12.0

 [[ 0.25       -0.25      ]
 [-0.66666667  1.        ]]

 [[10.]
 [14.]]


### Problem 2

In [40]:
#x + y = 6 and 6x + 3y = 30

A = np.array([[1,1],[6,3]])
b = np.array([[6],[30]])

#verfiy the size
print("dim. of matrix A=", A.shape)

#find the det(A)  
det= np.linalg.det(A)
print("\n", det)

#defining the inverse 
inv_A = np.linalg.inv(A) 
print("\n", inv_A)

#find the solution
sol = inv_A.dot(b)
print("\n",sol)

dim. of matrix A= (2, 2)

 -2.9999999999999996

 [[-1.          0.33333333]
 [ 2.         -0.33333333]]

 [[4.]
 [2.]]


### Problem 3

In [42]:
#x+y+z = 12000 and -y+z = 4000 and .03x+.04y+.07z = 670
A = np.array([[1,1,1],[-1,1,1],[.03,.04,.07]])
b = np.array([[12000],[4000],[670]])

#verfiy the size
print("dim. of matrix A=", A.shape)

#find the det(A)  
det= np.linalg.det(A)
print("\n", det)

#defining the inverse 
inv_A = np.linalg.inv(A) 
print("\n", inv_A)

#find the solution
sol = inv_A.dot(b)
print("\n",sol)

dim. of matrix A= (3, 3)

 0.060000000000000026

 [[  0.5         -0.5          0.        ]
 [  1.66666667   0.66666667 -33.33333333]
 [ -1.16666667  -0.16666667  33.33333333]]

 [[4000.        ]
 [ 333.33333333]
 [7666.66666667]]
