In [4]:
#matrix computation
import numpy as np

## Problem 1

In [5]:
#create a square matrix

x = np.array([[2,-14,8],[2,5,3]])
z = np.array([[8,5,1],[6,10,-3]])
print(x, "\n")
print(z)

[[  2 -14   8]
 [  2   5   3]] 

[[ 8  5  1]
 [ 6 10 -3]]


In [6]:
#multiplying matrices 
r_mul = x.__mul__(z)
print(r_mul)

[[ 16 -70   8]
 [ 12  50  -9]]


### Problem 2

In [7]:
#scalar product of a constant and matrix
lambda_value = -2
m = np.array([[-5,2,4],[6,10,-3],[-12,7,-2]])

scalar_value = lambda_value*m
print(scalar_value)

[[ 10  -4  -8]
 [-12 -20   6]
 [ 24 -14   4]]


### Problem 3

In [16]:
#det of a matrix
z = np.array([[2,-14,8],[2,5,3],[5,10,6]])

np.linalg.det(z)



-81.99999999999994

In [17]:
#det of a matrix
y = np.array([[8,5,7,9],[-2,12,6,6],[7,15,2,3],[5,-7,1,4]])

np.linalg.det(y)

-2026.0